### PR TITLE
Removed parameter tweaking, as NLog 4.4.2 works out of the box

### PR DESCRIPTION
**Pull request by snakefoot**
Added archive-performance test.

### CODE REVIEW

**Comment by 304NotModified** [comment]
but then it isn't a realistic test?

**Comment by snakefoot** [comment]
> but then it isn't a realistic test?

I was thinking that it was testing the performance of NLog, and not of the disk-drive

**Comment by 304NotModified** [comment]
good point, but there a several ways to write to disk, and then we cannot see the performance change between it.

**Comment by snakefoot** [comment]
I guess that was true before the SSD disk, as everything is memory to memory now with Windows file cache etc. (At least with keepFileOpen=true and concurrentWrites=false)

But yes it skips the testing of the actual FileAppenders. Will remove the discardAll flag again, and just use it locally :)

**Comment by snakefoot** [comment]
@304NotModified discardAll has been removed from the commit. Now it will also exercise the FileAppenders.

**Comment by 304NotModified** [comment]
👍

**Pull request merged**
